"""empty message

Revision ID: b2e64e401aaa
Revises: 
Create Date: 2018-03-17 14:27:33.505070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e64e401aaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provice',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('city',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('provice', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provice'], ['provice.pid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('village',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.cid'], ),
    sa.PrimaryKeyConstraint('vid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('village')
    op.drop_table('city')
    op.drop_table('provice')
    # ### end Alembic commands ###
